apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perf-sentinel-hub.name" . }}
data:
  appsettings.Production.json: |-
    {{- $sources := list }}
    {{- range .Values.sources }}
    {{- $sources = append $sources (dict "Id" .id "Name" .name "Environment" .environment "BaseUrl" .baseUrl "AuthHeaderName" .authHeaderName) }}
    {{- end }}
    {{ dict "Hub" (dict "DatabasePath" "/data/hub.db" "PollInterval" .Values.hub.pollInterval "HttpTimeout" .Values.hub.httpTimeout "MaxConcurrentPolls" .Values.hub.maxConcurrentPolls "Retention" .Values.hub.retention "DefaultReadLimit" .Values.hub.defaultReadLimit "MaxReadLimit" .Values.hub.maxReadLimit "Sources" $sources) | toJson }}
